let User,CustomErrorHandler;_7d9‍.x([["default",()=>_7d9‍.o]]);_7d9‍.w("../models",[["User",["User"],function(v){User=v}]]);_7d9‍.w("../Services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const admin  = async(req , res , next) =>{
    try {
        // our auth.js is giving us req.user._id
        const user = await User.findOne({_id :req.user._id});
        _7d9‍.g.console.log(user);
        if(user.role=="admin"){
            next();
        }else{
            return next (CustomErrorHandler.unAuthorized());
        }

    }
    catch (err){
        return next(CustomErrorHandler.serverError())
    }
}
_7d9‍.d(admin);